kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chabot2-oct24-1-imagestream-job-rolebinding
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: chabot2-oct24-1-dsp-job
    namespace: chabot2-oct24-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chabot2-oct24-1-imagestream-job-role
