---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: chabot2-oct24-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chabot2-oct24-1 
  name: chabot2-oct24-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi